Repository antvis/L7VP, pull requests merged in 2023-07, with the labels that each got.

#5 docs: 如何启动案例
  README.en-US.md
  README.md
Labels: documentation

#6 chore: update package desc
  packages/li-analysis-assets/package.json
  packages/li-core-assets/package.json
  packages/li-editor/package.json
  packages/li-p2/package.json
  packages/li-sdk/package.json
Labels: ignore-for-release

#8 fix: 上传文件列表样式
  packages/li-editor/src/widgets/UploadDataset/UploadDatasetList/index.less
Labels: bugfix

#9 fix: 检测数据集文本中的 WKT 情况
  examples/builder/.umirc.ts
  packages/li-editor/docs/case/Extend/demos/add-dataset/CustomAddDataset/CustomAddDataset.less
  packages/li-editor/docs/common/application.ts
  packages/li-editor/docs/common/my-assets/BubbleLayer/register-form/coordinate-schema.ts
  packages/li-editor/docs/common/my-assets/BubbleLayer/register-form/index.ts
  packages/li-editor/docs/common/my-assets/BubbleLayer/register-form/schema.ts
  packages/li-editor/docs/common/my-assets/ChoroplethLayer/register-form/coordinate-schema.ts
  packages/li-editor/docs/common/my-assets/ChoroplethLayer/register-form/index.ts
  packages/li-editor/docs/common/my-assets/ChoroplethLayer/register-form/schema.ts
  packages/li-editor/docs/dev/Default/demos/application.ts
  packages/li-editor/docs/dev/Service/demos/CustomAddDataset/CustomAddDataset.less
  packages/li-editor/src/hooks/useEditorState.ts
  packages/li-editor/src/utils/dataset-parser/data-parser.ts
  packages/li-editor/src/widgets/Export/ExportData/helper.ts
  packages/li-editor/src/widgets/FiltersPanel/FiltersPanel.tsx
  packages/li-editor/src/widgets/WidgetsPanel/WidgetAttribute/WidgetForm/SchemaField.tsx
  packages/li-sdk/src/utils/dataset-parser/geo-parser.ts
Labels: bugfix

#11 chore: docs badgen link
  README.en-US.md
  README.md
Labels: ignore-for-release

#13 fix: 属性表单组件丢失
  packages/li-editor/src/widgets/WidgetsPanel/WidgetAttribute/WidgetForm/SchemaField.tsx
Labels: bugfix
