Repository antvis/L7VP, pull requests merged in 2023-11, with the labels that each got.

#68 fix: 标签样式支持描边宽度与描边宽颜色
  packages/li-analysis-assets/src/layers/ChinaAdminLayer/Component.tsx
  packages/li-analysis-assets/src/layers/ChinaAdminLayer/index.tsx
  packages/li-analysis-assets/src/layers/ChinaAdminLayer/register-form/admin-label-schema.ts
  packages/li-analysis-assets/src/layers/ChinaAdminLayer/register-form/index.ts
  packages/li-p2/src/LayerAttribute/BubbleLayerStyle/helper.ts
  packages/li-p2/src/LayerAttribute/ChoroplethLayerStyle/helper.ts
  packages/li-p2/src/LayerAttribute/IconImageLayerStyle/helper.ts
  packages/li-p2/src/LayerAttribute/common-schema/label-collapse.ts
Labels: bugfix

#71 fix: 蜂窝图层样式配置问题
  packages/li-p2/src/LayerAttribute/GridLayerStyle/helper.ts
  packages/li-p2/src/LayerAttribute/HexbinLayerStyle/helper.ts
Labels: bugfix

#67 fix: 给图层描边宽度加限制
  README.en-US.md
  README.md
  bindings/pyl7vp/README.md
  bindings/pyl7vp/README.zh-CN.md
  packages/li-core-assets/src/layers/BubbleLayer/index.tsx
  packages/li-core-assets/src/layers/ChoroplethLayer/index.tsx
  packages/li-p2/src/LayerAttribute/common-schema/label-collapse.ts
  packages/li-p2/src/LayerAttribute/common-schema/stroke-collapse.ts
  packages/li-sdk/package.json
  packages/li-sdk/src/hooks/useDatasetFilter.ts
  packages/li-sdk/src/state/map.ts
Labels: bugfix

#74 feat: 数据栅格图层属性配置
  packages/li-analysis-assets/src/layers/SingleBandRasterLayer/demos/config.ts
  packages/li-analysis-assets/src/layers/SingleBandRasterLayer/register-form/domain-collapse.ts
  packages/li-analysis-assets/src/layers/SingleBandRasterLayer/register-form/fill-color-collapse.ts
  packages/li-analysis-assets/src/layers/SingleBandRasterLayer/register-form/index.ts
  packages/li-analysis-assets/src/layers/SingleBandRasterLayer/register-form/schema.ts
  packages/li-editor/src/widgets/LayersPanel/LayerAttribute/LayerForm/StyleForm.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomItem/Item/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomItem/Item/style.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomItem/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomItem/style.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/style.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/constants.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/demos/default.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/helper.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/index.md
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/style.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/type.ts
  packages/li-p2/src/LayerAttribute/components/index.ts
  packages/li-p2/src/LayerAttribute/index.ts
  packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/style.ts
  packages/li-p2/src/components/Formily/Offset/index.tsx
  packages/li-p2/src/components/Formily/Offset/style.ts
  packages/li-p2/src/components/Formily/Slider/style.ts
  packages/li-p2/src/components/Formily/SliderRange/index.tsx
  packages/li-p2/src/components/Formily/SliderRange/style.ts
Labels: bugfix

#72 fix: scale 初始填充问题
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/index.tsx
Labels: bugfix

#75 feat: 单波段栅格图层属性面板
  examples/builder/.umirc.ts
  packages/li-analysis-assets/package.json
  packages/li-analysis-assets/src/layers/SingleBandRasterLayer/Component.tsx
  packages/li-analysis-assets/src/layers/SingleBandRasterLayer/demos/config.ts
  packages/li-analysis-assets/src/layers/SingleBandRasterLayer/demos/index.tsx
  packages/li-analysis-assets/src/layers/SingleBandRasterLayer/index.md
  packages/li-analysis-assets/src/layers/SingleBandRasterLayer/index.tsx
  packages/li-analysis-assets/src/layers/SingleBandRasterLayer/register-form/domain-collapse.ts
  packages/li-analysis-assets/src/layers/SingleBandRasterLayer/register-form/index.ts
  packages/li-analysis-assets/src/layers/SingleBandRasterLayer/register-form/schema.ts
  packages/li-analysis-assets/src/layers/index.ts
  packages/li-editor/src/widgets/LayersPanel/LayerAttribute/LayerForm/StyleForm.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomItem/Item/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomItem/Item/style.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomItem/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomItem/style.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/style.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/constants.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/demos/default.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/helper.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/index.md
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/style.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/type.ts
  packages/li-p2/src/LayerAttribute/components/index.ts
  packages/li-p2/src/LayerAttribute/index.ts
  packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/style.ts
  packages/li-p2/src/components/Formily/Offset/index.tsx
  packages/li-p2/src/components/Formily/Offset/style.ts
  packages/li-p2/src/components/Formily/Slider/style.ts
  packages/li-p2/src/components/Formily/SliderRange/index.tsx
  packages/li-p2/src/components/Formily/SliderRange/style.ts
Labels: feature

#76 fix: 基础布局样式
  packages/li-core-assets/src/widgets/BaseLayout/ComponenStyle.ts
  packages/li-core-assets/src/widgets/BaseLayout/Component.less
  packages/li-core-assets/src/widgets/BaseLayout/Component.tsx
Labels: bugfix

#69 fix: 色带选择器样式优化
  packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/ColorPaletteGroup/style.ts
  packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/CustomRange/RangeItem/index.tsx
  packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/CustomRange/RangeItem/style.ts
  packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/DropDownContent.tsx
Labels: bugfix

#78 fix: 栅格瓦片支持高程数据格式
  packages/li-sdk/src/specs/dataset.ts
Labels: bugfix

#81 fix: 城市点击失效问题
  packages/li-analysis-assets/src/widgets/AdministrativeSelectControl/Component/index.tsx
  packages/li-analysis-assets/src/widgets/AdministrativeSelectControl/constant.ts
Labels: bugfix

#80 fix: 行政区域 CDN 数据源未同步完整，切换新 CDN 数据源
  packages/li-analysis-assets/src/widgets/AdministrativeSelectControl/Component/index.tsx
  packages/li-analysis-assets/src/widgets/AdministrativeSelectControl/constant.ts
Labels: bugfix

#77 fix: 优化自定义颜色划分，留更多空间
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomInput/InputCat/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomInput/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomInput/style.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomItem/Item/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomItem/Item/style.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/style.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/index.md
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomInput/InputNumber/index.tsx
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomInput/InputNumber/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomInput/InputString/index.tsx
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomInput/index.tsx
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomInput/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomItem/Item/index.tsx
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomItem/Item/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/index.tsx
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/index.tsx
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/style.ts
Labels: bugfix

#84 fix: label stroke 默认值
  packages/li-analysis-assets/src/layers/ChinaAdminLayer/index.tsx
  packages/li-analysis-assets/src/layers/ChinaAdminLayer/register-form/admin-label-schema.ts
  packages/li-p2/src/LayerAttribute/common-schema/label-collapse.ts
Labels: bugfix

#83 fix: 颜色划分组件自定义优化
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomCat/CustomItem/InputCat/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomCat/CustomItem/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomCat/CustomItem/style.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomCat/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomCat/style.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomNumber/CustomItem/InputNumber/index.tsx
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomNumber/CustomItem/InputNumber/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomNumber/CustomItem/index.tsx
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomNumber/CustomItem/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomNumber/index.tsx
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomNumber/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomString/CustomItem/InputString/index.tsx
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomString/CustomItem/index.tsx
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomString/CustomItem/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomString/index.tsx
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomString/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/index.tsx
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/index.tsx
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/style.ts
  packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/ColorPaletteGroup/style.ts
  packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/CustomRange/index.tsx
  packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/CustomRange/style.ts
  packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/DropDownContent.tsx
Labels: bugfix

#87 fix: 初始化图层类型未触发更新情况
  packages/li-analysis-assets/src/layers/ChinaAdminLayer/register-form/index.ts
  packages/li-analysis-assets/src/layers/FlowLayer/register-form/index.ts
  packages/li-analysis-assets/src/widgets/PropertiesPanel/registerForm.ts
  packages/li-core-assets/src/layers/ArcLayer/register-form/index.ts
  packages/li-core-assets/src/layers/BubbleLayer/register-form/index.ts
  packages/li-core-assets/src/layers/ChoroplethLayer/register-form/index.ts
  packages/li-core-assets/src/layers/GridLayer/register-form/index.ts
  packages/li-core-assets/src/layers/H3HexagonLayer/register-form/index.ts
  packages/li-core-assets/src/layers/HeatmapLayer/register-form/index.ts
  packages/li-core-assets/src/layers/HexbinLayer/register-form/index.ts
  packages/li-core-assets/src/layers/IconLayer/register-form/index.ts
  packages/li-core-assets/src/layers/LineLayer/register-form/index.ts
  packages/li-core-assets/src/widgets/LayerPopup/registerForm.ts
  packages/li-editor/src/utils/spec.ts
  packages/li-editor/src/utils/validator.ts
  packages/li-editor/src/widgets/DatasetsPanel/DatasetList/DatasetItem/index.tsx
  packages/li-editor/src/widgets/LayersPanel/LayerAttribute/LayerForm/StyleForm.tsx
  packages/li-editor/src/widgets/LayersPanel/LayerAttribute/LayerForm/index.tsx
  packages/li-editor/src/widgets/LayersPanel/LayerAttribute/index.tsx
  packages/li-editor/src/widgets/LayersPanel/helper.ts
  packages/li-p2/src/components/Formily/FieldSelect/Select/index.tsx
  packages/li-p2/src/components/Formily/Slider/index.tsx
  packages/li-sdk/src/components/internal/WrapperLayer/hooks/useLayerProps.ts
  packages/li-sdk/src/specs/layer.ts
Labels: bugfix

#86 fix: 数据处理函数
  packages/li-editor/src/widgets/FetchDataset/FetchDataset.tsx
  packages/li-editor/src/widgets/FetchDataset/ProcessingFunction/helper.ts
  packages/li-editor/src/widgets/FetchDataset/ProcessingFunction/index.less
  packages/li-editor/src/widgets/FetchDataset/ProcessingFunction/index.tsx
  packages/li-editor/src/widgets/FetchDataset/helper.ts
  packages/li-editor/src/widgets/FetchDataset/types.ts
Labels: bugfix

#89 chore: 添加标记图标
  examples/builder/src/constans/projects.ts
  packages/li-p2/src/LayerAttribute/components/IconScaleSelector/constant.ts
Labels: ignore-for-release
