Repository antvis/L7VP, pull requests merged in 2023-09, with the labels that each got.

#22 fix: 添加案例图层样式丢失问题
  packages/li-analysis-assets/src/widgets/DrawControl/Component/DrawTool.tsx
  packages/li-analysis-assets/src/widgets/FilterWidget/Component/FilterCard/index.tsx
  packages/li-analysis-assets/src/widgets/LegendWidget/Component.tsx
  packages/li-analysis-assets/src/widgets/SpreadSheetTable/Component/index.tsx
  packages/li-core-assets/src/layers/MVTLayer/mvt-layer.tsx
  packages/li-editor/src/widgets/DatasetsPanel/AddDataset/index.tsx
  packages/li-editor/src/widgets/FiltersPanel/FilterCard/index.tsx
  packages/li-p2/src/LayerAttribute/FlowLayerStyle/demos/default.tsx
  packages/li-p2/src/LayerAttribute/FlowLayerStyle/index.tsx
  packages/li-p2/src/LayerAttribute/FlowLayerStyle/types.ts
  packages/li-p2/src/LayerAttribute/components/IconList/index.tsx
  packages/li-p2/src/LayerAttribute/components/IconSelector/Internal/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/constants.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/index.tsx
  packages/li-p2/src/LayerAttribute/index.ts
  packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/CustomRange/RangeItem/index.tsx
  packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/constants/color-ranges.ts
  packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/style.ts
Labels: bugfix

#23 docs: 更新文档地址
  examples/builder/src/pages/Project/index.tsx
  packages/li-editor/src/widgets/UploadDataset/UploadDataset/index.tsx
  packages/li-sdk/src/specs/metadata.ts
  packages/li-sdk/src/utils/layer.ts
  packages/li-sdk/src/utils/service.ts
  packages/li-sdk/src/utils/widget.ts
Labels: documentation

#25 fix: 图表暗色主题样式问题
  packages/li-analysis-assets/src/widgets/AdministrativeSelectControl/index.ts
  packages/li-analysis-assets/src/widgets/DrawControl/index.tsx
  packages/li-analysis-assets/src/widgets/LegendWidget/index.tsx
  packages/li-analysis-assets/src/widgets/LocationSearchControl/index.tsx
  packages/li-analysis-assets/src/widgets/MeasureControl/index.tsx
  packages/li-analysis-assets/src/widgets/MiniChart/Component/Chart/helper.ts
  packages/li-analysis-assets/src/widgets/MiniChart/index.tsx
  packages/li-analysis-assets/src/widgets/PropertiesPanel/index.tsx
  packages/li-analysis-assets/src/widgets/SpreadSheetTable/index.tsx
  packages/li-analysis-assets/src/widgets/TimeLine/Component/TimeLineChart/index.tsx
  packages/li-analysis-assets/src/widgets/TimeLine/Component/index.tsx
  packages/li-core-assets/src/widgets/ExportImageControl/index.tsx
  packages/li-core-assets/src/widgets/FullscreenControl/index.tsx
  packages/li-core-assets/src/widgets/GeoLocateControl/index.tsx
  packages/li-core-assets/src/widgets/LayerPopup/index.tsx
  packages/li-core-assets/src/widgets/LogoControl/index.tsx
  packages/li-core-assets/src/widgets/MapThemeControl/index.tsx
  packages/li-core-assets/src/widgets/MapViewSettingControl/index.tsx
  packages/li-core-assets/src/widgets/MouseLocationControl/index.tsx
Labels: bugfix

#24 feat: 字段选择组件支持横向滚动
  packages/li-p2/src/components/Formily/FieldSelect/Select/index.tsx
  packages/li-p2/src/components/Formily/FieldSelect/Select/style.ts
Labels: feature

#29 fix: 属性面板资产无效数据情况
  package.json
  packages/li-analysis-assets/src/widgets/PropertiesPanel/ComponenStyle.ts
  packages/li-analysis-assets/src/widgets/PropertiesPanel/Component.tsx
  scripts/package-link.sh
Labels: bugfix

#30 fix: 高德修改对象引用问题
  packages/li-editor/src/hooks/internal/use-immer.ts
  packages/li-editor/src/layout/RuntimeApp/index.tsx
Labels: bugfix

#31 feat: 编辑器支持替换数据集
  packages/li-editor/src/types/widget.ts
  packages/li-editor/src/widgets/DatasetsPanel/AddDataset/AddDatasetModal.tsx
  packages/li-editor/src/widgets/DatasetsPanel/AddDataset/helper.ts
  packages/li-editor/src/widgets/DatasetsPanel/AddDataset/index.tsx
  packages/li-editor/src/widgets/DatasetsPanel/DatasetList/DatasetItem/index.tsx
  packages/li-editor/src/widgets/DatasetsPanel/DatasetList/index.tsx
  packages/li-editor/src/widgets/DatasetsPanel/DatasetsPanel.tsx
  packages/li-editor/src/widgets/DatasetsPanel/ReplaceDataset/index.tsx
Labels: feature

#32 chore: 修改属性名称
  packages/li-analysis-assets/src/widgets/FilterWidget/registerForm.ts
Labels: ignore-for-release

#34 fix: 修复替换数据集筛选器丢失
  packages/li-editor/src/layout/index.tsx
  packages/li-editor/src/widgets/DatasetsPanel/ReplaceDataset/index.tsx
  packages/li-p2/src/components/Filter/FilterList/index.tsx
Labels: bugfix

#35 fix: 修复 LayerPopup 点击时无法主动关闭
  lerna.json
  packages/li-core-assets/src/widgets/LayerPopup/ComponenStyle.ts
  packages/li-core-assets/src/widgets/LayerPopup/Component.tsx
Labels: bugfix

#36 fix: 修改筛选器遮挡问题
  packages/li-p2/src/components/Filter/FilterItem/index.tsx
Labels: bugfix

#37 fix: 选择组件样式问题
  examples/builder/src/constans/projects.ts
  packages/li-p2/src/components/Formily/ControlPositionSelect/Select/index.tsx
  packages/li-p2/src/components/Formily/ControlPositionSelect/Select/style.ts
  packages/li-p2/src/components/Formily/FieldSelect/Select/style.ts
Labels: bugfix

#39 fix: 蜂窝和网格图层聚合属性问题
  packages/li-core-assets/src/layers/GridLayer/register-form/coordinate-schema.ts
  packages/li-core-assets/src/layers/HexbinLayer/register-form/coordinate-schema.ts
Labels: bugfix

#41 chore: formily 升级
  packages/li-editor/package.json
  packages/li-p2/package.json
Labels: ignore-for-release

#43 fix: 修复 FlowLayer source 为空时的报错问题
  packages/li-analysis-assets/src/layers/FlowLayer/Component.tsx
Labels: bugfix

#45 chore: 修改 mvt 数据集元数据预览属性样式
  packages/li-editor/src/widgets/TilesetsDataset/MVTTile/index.tsx
Labels: ignore-for-release
