Repository antvis/L7VP, pull requests merged in 2023-08, with the labels that each got.

#14 fix: minChart 图表主题色可选择
  packages/li-analysis-assets/src/widgets/MiniChart/Component/Chart/IntervalLine.tsx
  packages/li-analysis-assets/src/widgets/MiniChart/Component/Chart/Pie.tsx
  packages/li-analysis-assets/src/widgets/MiniChart/Component/Chart/helper.ts
  packages/li-analysis-assets/src/widgets/MiniChart/Component/Chart/index.tsx
  packages/li-analysis-assets/src/widgets/MiniChart/Component/Chart/type.ts
  packages/li-analysis-assets/src/widgets/MiniChart/Component/index.tsx
  packages/li-analysis-assets/src/widgets/MiniChart/demos/config.ts
  packages/li-analysis-assets/src/widgets/MiniChart/index.tsx
  packages/li-analysis-assets/src/widgets/MiniChart/register-form/index.tsx
Labels: bugfix

#15 feat: support mvt layer
  .github/workflows/lint.yml
  packages/li-analysis-assets/.umirc.ts
  packages/li-analysis-assets/package.json
  packages/li-core-assets/.umirc.ts
  packages/li-core-assets/docs/dev/Editor/demos/config.ts
  packages/li-core-assets/docs/dev/Runtime/demos/config.ts
  packages/li-core-assets/package.json
  packages/li-core-assets/src/index.ts
  packages/li-core-assets/src/layers/MVTLayer/Component.tsx
  packages/li-core-assets/src/layers/MVTLayer/demos/config.ts
  packages/li-core-assets/src/layers/MVTLayer/demos/index.tsx
  packages/li-core-assets/src/layers/MVTLayer/index.md
  packages/li-core-assets/src/layers/MVTLayer/index.tsx
  packages/li-core-assets/src/layers/MVTLayer/mvt-layer.tsx
  packages/li-core-assets/src/layers/MVTLayer/register-form/index.ts
  packages/li-core-assets/src/layers/MVTLayer/register-form/schema.ts
  packages/li-core-assets/src/layers/MVTLayer/type.ts
  packages/li-core-assets/src/layers/index.ts
  packages/li-core-assets/src/widgets/LayerPopup/registerForm.ts
  packages/li-editor/.umirc.ts
  packages/li-editor/package.json
  packages/li-editor/src/widgets/DatasetsPanel/AddDataset/index.tsx
  packages/li-editor/src/widgets/DatasetsPanel/DatasetList/DatasetItem/index.tsx
  packages/li-editor/src/widgets/TilesetsDataset/MVTTile/index.tsx
  packages/li-editor/src/widgets/TilesetsDataset/TilesetsDataset.tsx
  packages/li-editor/src/widgets/TilesetsDataset/XYZTile/index.tsx
  packages/li-editor/src/widgets/TilesetsDataset/types.ts
  packages/li-editor/src/widgets/WidgetsPanel/WidgetList/WidgetGroup.tsx
  packages/li-sdk/package.json
  packages/li-sdk/src/components/internal/WrapperLayer/hooks/useLayerProps.ts
  packages/li-sdk/src/specs/dataset.ts
  packages/li-sdk/src/specs/layer.ts
Labels: feature

#17 docs: pyl7vp user guide link
  bindings/pyl7vp/pyl7vp/l7vp.py
Labels: documentation

#18 chore: add Google Analytics
  .github/workflows/lint.yml
  .github/workflows/pyl7vp-test.yml
  .github/workflows/release.yml
  bindings/pyl7vp/README.md
  bindings/pyl7vp/README.zh-CN.md
  bindings/pyl7vp/pyl7vp/l7vp.py
  bindings/pyl7vp/pyl7vp/meta.py
  bindings/pyl7vp/pyl7vp/templates/l7vp.html
  bindings/pyl7vp/setup.py
Labels: ignore-for-release
