Repository antvis/L7VP, pull requests merged in 2024-01, with the labels that each got.

#109 fix: 数值筛选器配置态更新问题
  packages/li-analysis-assets/src/widgets/FilterControl/Component/NumberItem.tsx
  packages/li-analysis-assets/src/widgets/FilterControl/Component/StringItem.tsx
  packages/li-analysis-assets/src/widgets/FilterControl/Component/index.tsx
  packages/li-analysis-assets/src/widgets/FilterControl/index.tsx
  packages/li-analysis-assets/src/widgets/FilterWidget/index.tsx
Labels: bugfix

#110 chore: 修正文件名
  examples/builder/src/constants/assets.ts
  examples/builder/src/constants/index.ts
  examples/builder/src/constants/projects.ts
  examples/builder/src/pages/App/index.tsx
  examples/builder/src/pages/Builder/index.tsx
  examples/builder/src/pages/Project/index.tsx
Labels: ignore-for-release

#112 feat: ResterScaleSelector 支持 linear 线性连续映射
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomCat/CustomItem/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/index.tsx
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/constants.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/helper.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/type.ts
Labels: feature

#115 fix: 修改设置卷帘对比控制逻辑
  packages/li-analysis-assets/src/widgets/SwipeControl/Component.tsx
  packages/li-analysis-assets/src/widgets/SwipeControl/registerForm.ts
Labels: bugfix

#114 feat: 卷帘支持设置默认对比图层
  packages/li-analysis-assets/src/widgets/SwipeControl/Component.tsx
  packages/li-analysis-assets/src/widgets/SwipeControl/registerForm.ts
Labels: feature

#117 fix: 图层图标样式大小统一
  packages/li-analysis-assets/src/layers/ChinaAdminLayer/index.tsx
  packages/li-analysis-assets/src/layers/FlowLayer/index.tsx
  packages/li-analysis-assets/src/layers/SingleBandRasterLayer/index.tsx
  packages/li-core-assets/src/layers/ArcLayer/index.tsx
  packages/li-core-assets/src/layers/BubbleLayer/index.tsx
  packages/li-core-assets/src/layers/ChoroplethLayer/index.tsx
  packages/li-core-assets/src/layers/GridLayer/index.tsx
  packages/li-core-assets/src/layers/H3HexagonLayer/index.tsx
  packages/li-core-assets/src/layers/HeatmapLayer/index.tsx
  packages/li-core-assets/src/layers/HexbinLayer/index.tsx
  packages/li-core-assets/src/layers/IconLayer/index.tsx
  packages/li-core-assets/src/layers/LineLayer/index.tsx
  packages/li-core-assets/src/layers/MVTLayer/index.tsx
  packages/li-core-assets/src/layers/TileLayer/index.tsx
  packages/li-editor/docs/common/my-assets/BubbleLayer/index.tsx
  packages/li-editor/docs/common/my-assets/ChoroplethLayer/index.tsx
  packages/li-editor/src/widgets/LayersPanel/LayerAttribute/BaseFormSchemaField/VisTypeSelect/VisTypeSelect.less
  packages/li-editor/src/widgets/LayersPanel/LayerList/LayerItem/index.less
Labels: bugfix

#119 fix: 卷帘、图例控件样式问题
  packages/li-analysis-assets/src/widgets/LegendWidget/ComponenStyle.ts
  packages/li-analysis-assets/src/widgets/SwipeControl/ComponenStyle.ts
Labels: bugfix

#121 fix: editor css
  packages/li-editor/src/components/EditName/index.less
  packages/li-editor/src/components/EditName/index.tsx
  packages/li-editor/src/components/EditName/style.ts
  packages/li-editor/src/layout/SideNav/NavMenu/index.less
  packages/li-editor/src/layout/SideNav/NavMenu/index.tsx
  packages/li-editor/src/layout/SideNav/NavMenu/style.ts
  packages/li-editor/src/layout/SideNav/index.less
  packages/li-editor/src/layout/SideNav/index.tsx
  packages/li-editor/src/layout/SideNav/style.ts
  packages/li-editor/src/layout/SidePanel/index.less
  packages/li-editor/src/layout/SidePanel/index.tsx
  packages/li-editor/src/layout/SidePanel/style.ts
Labels: bugfix

#124 fix: antd 变量
  packages/li-editor/src/widgets/LayersPanel/LayerList/LayerItem/style.ts
  packages/li-p2/src/LayerAttribute/components/ResterScaleSelector/CustomMappingColors/CustomCat/CustomItem/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomNumber/CustomItem/InputNumber/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomNumber/CustomItem/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomString/CustomItem/style.ts
  packages/li-p2/src/LayerAttribute/components/ScaleSelector/CustomMappingColors/CustomString/UnknownItem/style.ts
  packages/li-p2/src/components/Formily/ColorPicker/style.ts
  packages/li-p2/src/components/Formily/ColorRangeSelector/Internal/CustomRange/RangeItem/style.ts
Labels: bugfix

#127 fix: 时间轴重复多次添加筛选条件
  packages/li-analysis-assets/src/widgets/TimeLine/Component/TimeLineChart/index.tsx
  packages/li-core-assets/src/services/fetch-dataset/helper.ts
Labels: bugfix

#130 feat: pyl7vp 支持暗色模式
  bindings/pyl7vp/notebooks/GeoJSON.ipynb
  bindings/pyl7vp/pyl7vp/l7vp.py
  bindings/pyl7vp/pyl7vp/meta.py
  bindings/pyl7vp/pyl7vp/templates/l7vp.html
Labels: feature

#131 chore: 修改暗色背景色
  bindings/pyl7vp/pyl7vp/config.py
  bindings/pyl7vp/pyl7vp/meta.py
  bindings/pyl7vp/pyl7vp/templates/l7vp.html
  packages/li-editor/docs/case/Theme/demos/theme.ts
Labels: ignore-for-release

#132 fix: 字段选择组件多选问题修复
  packages/li-p2/src/components/Formily/FieldSelect/Select/index.tsx
  packages/li-p2/src/components/Formily/FieldSelect/index.tsx
  packages/li-p2/src/components/Formily/FilterConfiguration/FilterModal/FilterContent/index.tsx
Labels: bugfix

#133 fix: 资产市场数据源导出问题
  packages/li-editor/src/widgets/Export/ExportData/helper.ts
  packages/li-editor/src/widgets/Export/ExportData/index.tsx
Labels: bugfix

#135 fix: 地图倾角操作后添加新的控件报错
  packages/li-core-assets/src/widgets/MapViewSettingControl/Component.tsx
  packages/li-sdk/src/state/map.ts
Labels: bugfix

#134 fix: 属性面板重复渲染问题
  packages/li-editor/src/widgets/WidgetsPanel/WidgetAttribute/index.tsx
Labels: bugfix

#136 chore: 通过数据集实例获取 domain
  packages/li-editor/src/services/editor-dataset-manager.ts
  packages/li-editor/src/widgets/LayersPanel/LayerAttribute/LayerForm/index.tsx
  packages/li-editor/src/widgets/WidgetsPanel/WidgetAttribute/WidgetForm/index.tsx
  packages/li-editor/src/widgets/WidgetsPanel/WidgetAttribute/index.tsx
Labels: ignore-for-release

#137 fix: 线图层分类数据映射图例不显示问题
  packages/li-analysis-assets/src/widgets/LegendWidget/helper.ts
Labels: bugfix
